dataset_str:
  "ASEWAI(
    split='${dataset.ase_wai.val.split}',
    resolution=${dataset.ase_wai.val.dataset_resolution},
    principal_point_centered=${dataset.ase_wai.val.principal_point_centered},
    seed=${dataset.ase_wai.val.seed},
    transform='${dataset.ase_wai.val.transform}',
    data_norm_type='${dataset.ase_wai.val.data_norm_type}',
    ROOT='${dataset.ase_wai.val.ROOT}',
    dataset_metadata_dir='${dataset.ase_wai.val.dataset_metadata_dir}',
    overfit_num_sets=${dataset.ase_wai.val.overfit_num_sets},
    variable_num_views=${dataset.ase_wai.val.variable_num_views},
    num_views=${dataset.ase_wai.val.num_views},
    covisibility_thres=${dataset.ase_wai.val.covisibility_thres})"
split: 'val'
dataset_resolution: ${dataset.resolution_val_ase}
principal_point_centered: ${dataset.principal_point_centered}
seed: 777
transform: 'imgnorm'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/ase
dataset_metadata_dir: ${mapanything_dataset_metadata_dir}
overfit_num_sets: null
variable_num_views: ${dataset.val.variable_num_views}
num_views: ${dataset.num_views}
covisibility_thres: 0.25
