stage: # set stage via CLI
root: # path of wai-formatted dataset

gpus: 0
cpus: 10
mem: 20
scenes_per_job: 20
conda_env: # pass the name of our conda environment
nodelist:

stages:
  conversion:
    script: conversion/paralleldomain4d.py
    config: conversion/paralleldomain4d.yaml
  covisibility:
    script: covisibility.py
    config: covisibility/covisibility_gt_depth.yaml
    gpus: 1
